from pathlib import Path

configfile: "conf/config_ldsc.yaml"


def ws_path(file_path):
    return str(Path(config.get("path_base"), file_path))

def db_path(file_path):
    return str(Path(config.get("path_data"), file_path))

def ss_path(file_path):
    return str(Path(config.get("path_pwas"), file_path))


rule all:
    input:
        expand(
            ws_path("output/herit/herit.seq.{i}.regenie"),
            i=[i for i in config["sample_seqids"]]
        )


rule append_pvalue:
    input:
        ifile = ss_path("seq.{i}/seq.{i}.regenie.tsv.gz")
    output:
        ofile = ws_path("output/pwas/seq.{i}.regenie.gz")
    params:
        ifile = ss_path("seq.{i}/seq.{i}.regenie"),
        ofile = ws_path("output/pwas/seq.{i}regenie.gz")
    log:
        ws_path("logs/pwas/seq.{i}.regenie.gz.log")
    container:
        "docker://quay.io/biocontainers/plink2:2.00a5--h4ac6f70_0"
    shell:
        """
        zcat {params.ifile} | \
        awk 'BEGIN {{ OFS="\t" }} NR==1 {{ print $0, "P" }} NR>1 {{ print $0, 10^-$11 }}' | \
        gzip -c > {params.ofile} 2> {log}
        """


rule munge_sumstats:
    input:
        ifile = ws_path("output/pwas/seq.{i}.regenie.gz")
    output:
        ofile = ws_path("output/munge/seq.{i}.regenie.sumstats.gz")
    params:
        ofile = ws_path("output/munge/seq.{i}.regenie")
    log:
        ws_path("logs/munge/seq.{i}.regenie.gz.log")
    container:
        "docker://quay.io/biocontainers/plink2:2.00a5--h4ac6f70_0"
    shell:
        "source ~/.bashrc &&"
        "conda activate ldsc &&"
        "munge_sumstats.py "
        "--sumstats {input.ifile} "
        "--snp ID "
        "--a1 ALLELE0 "
        "--a2 ALLELE1 "
        "--p P "
        "--frq A1FREQ "
        "--N-col N "
        "--chunksize 500000 "
        "--a1-inc "
        "--out {params.ofile} "


rule compute_herit:
    input:
        munged = ws_path("output/munge/seq.{i}.regenie.sumstats.gz"),
    output:
        ofile  = ws_path("output/herit/herit.seq.{i}.regenie")
    params:
        ldfile = config['path_ldsc']
    log:
        ws_path("logs/herit/herit.seq.{i}.regenie.log")
    container:
        "docker://quay.io/biocontainers/plink2:2.00a5--h4ac6f70_0"
    shell:
        "source ~/.bashrc && " 
        "conda activate ldsc  && "
        "ldsc.py  "
        "    --h2  {input.munged} "
        "    --ref-ld-chr  {params.ldfile}@ "  
        "    --w-ld-chr  {params.ldfile}@ "
        "    --out  {output.ofile}  2> {log}"


# rule compute_herit:
#     input:
#         app = "/home/dariush.ghasemi/bin/ldsc/ldsc.py",
#         ifile = "data/test_prot1.22.cleaned.pip.sumstats.gz"
#         ldfile = "output/ld.subset_chr22_2"
#     output:
#         ofile = "output/ldsc_test_prot1.pip"
#     conda:
#         "ldsc"
#     shell:
#         "source ~/.bashrc &&"
#         "conda activate ldsc &&"
#         "python {input.app} "
# 		"--h2 {input.ifile} "
# 		"--ref-ld {input.ifile} "
# 		"--w-ld {input.ifile} "
# 		"--out {output.ofile} "