# paths
sumstat_path: "/group/diangelantonio/users/alessia_mapelli/QC_gen_INTERVAL/QC_steps/StepB/New_analysis/recomputed_stats/recoded"
report_path:  "/group/diangelantonio/users/alessia_mapelli/QC_gen_INTERVAL/QC_steps/StepB/New_analysis/Variants_QC/recoded"
#variant_list: "/home/dariush.ghasemi/projects/pqtl_pipeline_ldsc"