executor: slurm
jobs: 250
software-deployment-method:
   - conda
#   - apptainer
retries: 3
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
cores: &cores 8
latency-wait: 60
keep-going: True
rerun-incomplete: False
printshellcmds: True
scheduler: ilp

default-resources:
    slurm_partition: cpuq #cpu-interactive
    #slurm_account: ${USER}
    mem_mb: attempt * 512
    threads: 1
    runtime: attempt * 5

set-resources:
    recode_pgen:
        mem_mb: 102400 + attempt * 2048
        threads: *cores
    header_info:
        mem_mb: 2048 + attempt * 2048
    selected_sample:
      mem_mb: 102400 + attempt * 2048
      threads: *cores
    filter_var:
      mem_mb: 102400 + attempt * 2048
      threads: *cores
    create_bgen:
      mem_mb: 102400 + attempt * 2048
      threads: *cores
    qctool:
      mem_mb: 1024 + attempt * 1024
      threads: *cores
    get_hq_variants:
      mem_mb: 2048 + attempt * 2048
      threads: *cores
    filter_hq_variants:
      mem_mb: 102400 + attempt * 2048
      threads: *cores
    merge_filter_hq_variants:
      mem_mb: 102400 + attempt * 2048
      threads: *cores
    compute_ld:
      mem_mb: 124928 + attempt * 4098
      threads: *cores
